### ISSUE TITLE
Rake routes doesn't work with with Grape 0.19

### ISSUE THREAD

**Issue by fatmcgav** [ruby-grape/grape-on-padrino#3]
I've tried running this example using the latest release of Grape, however `rake routes` fails with:
`method_missing': undefined method request_methods'`
Full stack trace below...

Any suggestions on how to fix?

Cheers

> padrino rake routes
=> Executing Rake routes ...
WARNING! In Padrino >= 0.14.0 cli command `padrino rake` will NOT add
'./lib' folder to $LOAD_PATH. Please alter your `require` calls accordingly
if you depend on this behavior.
  DEVEL - 11/Feb/2017 15:15:23  LOADING (0.0123s) /Users/gavinw/scratch/grape-on-padrino/api/api.rb
  DEVEL - 11/Feb/2017 15:15:23 Removed constant Acme::Api::Api from Acme::Api
  DEVEL - 11/Feb/2017 15:15:23 Cyclic dependency reload for NameError: uninitialized constant Acme::Api::Ping
  DEVEL - 11/Feb/2017 15:15:23  LOADING (0.0096s) /Users/gavinw/scratch/grape-on-padrino/api/ping.rb
  DEVEL - 11/Feb/2017 15:15:23  LOADING (0.0080s) /Users/gavinw/scratch/grape-on-padrino/api/pingv2.rb
  DEVEL - 11/Feb/2017 15:15:23  LOADING (0.0177s) /Users/gavinw/scratch/grape-on-padrino/api/api.rb
  DEVEL - 11/Feb/2017 15:15:23 Loaded Padrino in 0.732267 seconds
/Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/grape-0.19.1/lib/grape/router/route.rb:27:in `method_missing': undefined method `request_methods' for #<Grape::Router::Route:0x007fb2319b3a80> (NoMethodError)
Did you mean?  request_method
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/padrino-core-0.13.3.3/lib/padrino-core/mounter.rb:133:in `block in named_routes'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/padrino-core-0.13.3.3/lib/padrino-core/mounter.rb:132:in `map'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/padrino-core-0.13.3.3/lib/padrino-core/mounter.rb:132:in `named_routes'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/padrino-core-0.13.3.3/lib/padrino-core/cli/rake_tasks.rb:24:in `list_app_routes'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/padrino-core-0.13.3.3/lib/padrino-core/cli/rake_tasks.rb:54:in `block (2 levels) in <top (required)>'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/padrino-core-0.13.3.3/lib/padrino-core/cli/rake_tasks.rb:53:in `each'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/padrino-core-0.13.3.3/lib/padrino-core/cli/rake_tasks.rb:53:in `block in <top (required)>'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/task.rb:250:in `blockin execute'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/task.rb:194:in `blockin invoke_with_call_chain'
        from /Users/gavinw/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/application.rb:152:in`invoke_task'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/application.rb:108:in`block (2 levels) in top_level'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/application.rb:108:in`each'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/application.rb:108:in`block in top_level'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/application.rb:117:in`run_with_threads'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/rake-12.0.0/lib/rake/application.rb:102:in`top_level'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/padrino-core-0.13.3.3/lib/padrino-core/cli/base.rb:23:in `rake'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/gems/padrino-core-0.13.3.3/bin/padrino:9:in `<top (required)>'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/bin/padrino:22:in `load'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/bin/padrino:22:in `<main>'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/bin/ruby_executable_hooks:15:in `eval'
        from /Users/gavinw/.rvm/gems/ruby-2.3.3@padrino/bin/ruby_executable_hooks:15:in `<main>'

**Comment by dblock** [comment]
Fixed in #4. The `Route` namespace has changed in Grape, moving to `Grape::Routes::Route`, and `route.controller` no longer returned `nil`, which was the default for missing methods in the route that could store all kinds of stuff. I also had to fix the deprecation where `route_path` became `path`, `route_version` became `version` and `route_method` became `request_method`.

**Comment by fatmcgav** [comment]
@dblock Cheers for the quick fix :)
